### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AlexanderAbair** [ssteelecabrera/ssteelecabrera_PS3#1]
I may have submitted my comments 10-15 times in Canvas...  Sorry if that's the case.  At any rate, everything works great in your python script except the date and time output in your final print commands for problems 2 and 3.  I've attached some alternative code that you can put into your problems 2 and 3 to fix the issue.  Otherwise, everything looks good!

# Here's my addition to your code
    date_and_time = line.split(',')[0]
    time = date_and_time[11:]
    date = date_and_time[0:10]

**Comment by ssteelecabrera** [comment]
Hi Alex,

Thanks for adding your peer review here! I don't think I am able to view it in Canvas so I appreciate that you took the time to add it here.

Regards,
Sarah
